# Generated by Django 5.1.6 on 2025-02-12 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0003_categories_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='haven.categories'),
        ),
    ]
