# Generated by Django 5.1.6 on 2025-02-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0004_alter_article_categorys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
