# Generated by Django 5.1.6 on 2025-02-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0006_comment_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='article',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
